profile.php, resources/css/styles.css
Added some media screens to css but styles only work correctly with viewports of 1920px and above.
Progression on the player profile page.
Still needs some work.
=> Player Profile Page

profile.php, resources/css/styles.css
Repositioned elements back into their normal places.
Completed the player history table.
Added view more button (goes nowhere).
=> profile page

classes/content-manager.php, get-states-by-country-ID.php, javascript/scripts.js, upload-event.php
drop down boxes for states and country work now. please see slack for request for help
=> upload events state and country selects

javascript/scripts.js, upload-event.php
Changes made as suggested by James
=> Changes on event page

classes/content-manager.php, classes/maple-file-manager.php, profile.php
Changes to make profile page dynamic. 
emergency changes that means maple execution is not queued but rather is simply updated immediately. (this will need to be rectified as will cause lag for the user, however, was required for demo purposes). This is because Utas block changes to /etc/at.allow
Grant please review before merging.
=> emergency changes made prior to sem 1 presentation.

javascript/scripts.js
Uses html5 validity messages to alert user of errors in their data entry. Sets max date of event to today.
=> Client side validity checking match upload

configurations/config.ini, players.php, process-player-list.php
functionality for player searching semi-done
=> player search filter

classes/content-manager.php, process-event.php
All fields in the upload matches form are validated on the server before uploaded and used with maple.
=> Upload Event Server-Side Validation

classes/account.php, clubs.php, includes/footer.php, includes/notification-modal.php, includes/notifications.php, javascript/scripts.js, resources/css/styles.css
Popup notifications are now fully implemented.
=> Popup Notifications

ajax.php, classes/content-manager.php, classes/database.php, javascript/scripts.js, profile.php, resources/css/styles.css
Small rearrangement of profile page. Now dynamic. Fully functional.
=> Dynamic Profile Page

configurations/testing/test_build_database.sql
minor issues with dummy values. clubs were not given sport_id s.
=> fixed dummy insert values

upload-event.php
Harry had hard coded popups in the upload-event.php but it was designed by adib to be included so easily changed.
=> removed hard coded popups

classes/content-manager.php, get-states-by-country-ID.php, javascript/pagination.js, javascript/scripts.js, players.php, process-player-list.php, resources/css/styles.css
Player search is completely done. Everything works perfectly.
=> Fixed all minor issues

classes/content-manager.php, maple/mapletournamentProcess.php, maple/tournamentProcessDouble.php
Will now run maple for doubles event. Match results etc will be updated in the db.
=> Maple-Doubles

classes/content-manager.php, configurations/config.ini
=> fix missing ;

classes/content-manager.php, classes/maple-file-manager.php, maple/tournamentProcess.php, maple/tournamentProcessDouble.php
maple now works for all events types, tested on server with actual maple running.
=> Maple Working

classes/account.php, classes/content-manager.php, javascript/scripts.js, process-event.php, upload-event.php
Upload event no longer has sport selection, this is obtained from logged in account. plays_at table is updated on match upload.
=> upload event  fixes

ajax.php, classes/content-manager.php, configurations/config.ini, javascript/scripts.js, process-player-list.php, profile.php, resources/css/styles.css, team-profile.php
can search by family name
fixed some styling issues.
=> Player doubles profile

classes/content-manager.php, javascript/scripts.js, profile.php, resources/css/styles.css, team-profile.php
Styling for both team profile and player profile are complete to the best they can be currently.
=> Finished styling profile pages

classes/content-manager.php, configurations/testing/build_database.sql, configurations/testing/test_build_database.sql, includes/notifications.php, javascript/scripts.js, process-event.php
Set score inputs into database for doubles and singles matches. Updated database structure. Shows confirmation on match upload.
=> Set score upload

account.php, classes/content-manager.php, configurations/testing/build_database.sql, configurations/testing/test_build_database.sql, javascript/scripts.js
Fix profile page showing ratings as floats.
Update club info to club management on account page
Update database schema, remove unique constraint on state name.
=> Profile page fix, account page fix, database schema

profile.php
whilst planning presentation came across minor error. Fixed.
=> profile page fix

index.php, javascript/pagination.js, players.php
Home page search working by posting data to players page and then using js to submit search.
=> Home Page Search Working

includes/privacy-policy.txt, includes/terms-and-conditions.txt, privacy-policy.php, terms-and-conditions.php
The above pages filled with data. Allowing client to edit .txt files.
=> Terms and Condition and Policies

javascript/scripts.js, resources/css/styles.css
=> fixed the css issues coming

ajax.php, classes/content-manager.php, configurations/config.ini, javascript/scripts.js, profile.php, resources/css/styles.css, team-profile.php
Added Biography info for players which includes only their: Player Name, Gender, and Age.
Select sport functionality is working
Completed the styling
=> Team Profile Page

classes/content-manager.php, clubs.php, events.php, index.php, javascript/scripts.js
event and club search now works including from home page
=> event and club search

resources/css/styles.css
=> fixed alignment of delete button

javascript/scripts.js
This is to help with instructions for adib and generally good practice anyway.
=> give hidden field a class

classes/account.php, classes/content-manager.php, configurations/testing/build_database.sql, configurations/testing/test_build_database.sql, includes/nav-menu-signed-in.php, includes/notifications.php, javascript/scripts.js, manage-club-exp.php, process-event.php, upload-event.php
Club expiration now implemented. 
*Note* DB change
Minor change to fix home state selection on upload event page as this broke create club selection.
=> club expiration

process-event.php, upload-event.php
admins can now upload events. They must select the club they are uploading for and the sport.
=> admin upload event

process-event.php, upload-event.php
Reverts GrantUpson/Sports-CMS#104
=> Revert "admin upload event"

includes/footer.php, includes/header.php, includes/nav-menu-signed-in.php, includes/nav-menu-signed-out.php, javascript/scripts.js, resources/css/styles.css, upload-event.php
Reverts GrantUpson/Sports-CMS#103
=> Revert "Popover for help"

account-pagination.php, ajax.php, classes/content-manager.php, includes/notifications.php, javascript/scripts.js, upload-event.php
data will now be prefilled into edit event form
=> edit upload event prefill data

classes/content-manager.php, process-event.php
=> process edit event complete

account.php, ajax.php, classes/account.php, includes/edit-account-modal.php, includes/notifications.php
account info can now be updated
=> personal info update

classes/content-manager.php
fixed add rating for players with rating of zero.
=> adib noted problem with add rating

classes/content-manager.php
The date has been updated in event section and 'view club members' in the `club-Administration ` panel
=> date_format changed as per request of client

javascript/scripts.js, upload-event.php
updated event name to 30 chars. set scores now required.
=> field validation complete

includes/register-modal.php, resources/css/styles.css
add information on create account page to inform user
=> inform user

classes/content-manager.php
player ratings now integers. players now showing up only once
=> admin bugs

classes/content-manager.php, javascript/pagination.js, javascript/scripts.js, players.php, process-player-list.php, resources/css/styles.css
Display bookmarked players seems to be working
=> Favourite player list
